### ISSUE TITLE
Trocar lib AFNetworking por Alamofire

### ISSUE THREAD

**Issue by DamascenoRafael** [caronae/caronae-ios#12]
Atualmente toda a comunicação com o servidor do Caronaê é feita através da lib [AFNetworking](https://github.com/AFNetworking/AFNetworking). Como o Caronaê se encontra quase que totalmente em swift o objetivo é migrar este uso para a lib [Alamofire](https://github.com/Alamofire/Alamofire).

## Detalhes

Toda a parte de Rede do Caronaê está localizada em `Caronae > Services`, neste grupo existem módulos de comunicação separados. Todos estes Services utilizam uma instância de `CaronaeAPIHTTPSessionManager.swift` localizada em `Caronae > Networking`

**Comment by fcrespo82** [comment]
Olá @DamascenoRafael encontrei seu repositório pelo post da [Jessica temporal](https://medium.com/@jessicatemporal/projetos-brasileiros-para-contribuir-nesse-hacktoberfest-versão-2018-4925959b9411) sobre o #Hacktoberfest. Já sou desenvolvedor mas estou começando em Swift. Gostaria de ajuda com este issue?

**Comment by fcrespo82** [comment]
Ok, vou atrás disso. Assim que tiver algo para testar abro um PR e em caso de dúvida na arquitetura chamo você aqui para discutirmos como proceder.

**Comment by fcrespo82** [comment]
Como posso testar o app no ambiente de dev? Preciso de um usuario na api.dev.caronae.org?

**Comment by DamascenoRafael** [comment]
@fcrespo82, no ambiente de dev você pode selecionar "Entrar manualmente" e utilizar identificação e chave `123` ou então `007`, são 2 usuários genéricos de teste.

**Comment by DamascenoRafael** [comment]
Implementado no PR #25. Obrigado @fcrespo82!

**Comment by fcrespo82** [comment]
Eu que agradeço a oportunidade de aprender um pouquinho de Swift! Que bom que pude ajudar!!
